-- 添加乐观锁版本列（PostgreSQL）
-- 为已有表增加 version 列，默认 0，非空

ALTER TABLE IF EXISTS products
    ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 0;

ALTER TABLE IF EXISTS warehouses
    ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 0;

ALTER TABLE IF EXISTS warehouse_products
    ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 0;


